import json

# Build the complete JSON structure
data = {
    "metadata": {
        "version": "1.0.0",
        "last_updated": "2026-05-14",
        "description": "Symptom combination to disease mapping for AI healthcare training",
        "total_combinations": 625,
        "symptoms_count": 25
    },
    "symptoms": [
        "Fever", "Cough", "Headache", "Fatigue", "Sore Throat", "Runny Nose", "Chest Pain",
        "Shortness of Breath", "Nausea", "Vomiting", "Diarrhea", "Abdominal Pain", "Back Pain",
        "Joint Pain", "Muscle Pain", "Dizziness", "Rash", "Itching", "Swelling", "Blurred Vision",
        "Hearing Loss", "Insomnia", "Anxiety", "Depression", "Wheezing"
    ],
    "diseases": [
        "Common Cold", "Viral Fever", "Migraine", "Tonsillitis", "Pneumonia", "Food Poisoning",
        "Infection", "Typhoid", "Viral Infection", "Chickenpox", "Bronchitis", "Asthma",
        "Indigestion", "Heart Condition", "Anemia", "Dry Cough", "Cough Syndrome", "Tension Headache",
        "Chronic Fatigue", "Angina", "Allergy", "Anaphylaxis", "Vertigo", "Skin Allergy", "Rash",
        "Edema", "Hearing Loss", "Sleep Disorder", "Stress", "Mental Stress", "Arthritis", "Back Pain",
        "Muscle Strain", "Dietary", "Diabetes", "Acidity"
    ]
}

# Build symptom_disease_mapping
symptoms = data["symptoms"]
disease_map = {}

# Base mappings for each symptom
base_diseases = {
    "Fever": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Cough": {"Fever": "Common Cold", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Headache": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Fatigue": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Sore Throat": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Runny Nose": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Chest Pain": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Shortness of Breath": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Nausea": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Vomiting": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Diarrhea": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Abdominal Pain": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Back Pain": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Joint Pain": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Muscle Pain": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Dizziness": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Rash": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Itching": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Swelling": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Blurred Vision": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Hearing Loss": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Insomnia": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Anxiety": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Depression": {"Fever": "Viral Fever", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"},
    "Wheezing": {"Fever": "Common Cold", "Cough": "Common Cold", "Headache": "Tension Headache", "Fatigue": "Weakness / Tiredness", "Sore Throat": "Throat Infection", "Runny Nose": "Cold / Allergies", "Chest Pain": "Acidity / Gas", "Shortness of Breath": "Breathing Problem", "Nausea": "Stomach Upset", "Vomiting": "Food Poisoning", "Diarrhea": "Loose Motion", "Abdominal Pain": "Stomach Pain", "Back Pain": "Muscle Strain", "Joint Pain": "Body Pain", "Muscle Pain": "Body Ache", "Dizziness": "Low BP / Weakness", "Rash": "Skin Allergy", "Itching": "Allergy", "Swelling": "Inflammation", "Blurred Vision": "Eye Strain", "Hearing Loss": "Ear Blockage", "Insomnia": "Sleep Problem", "Anxiety": "Stress", "Depression": "Mental Stress", "Wheezing": "Asthma / Allergy"}
}

# Create a complete mapping for each symptom
for map_name, mapping in base_diseases.items():
    disease_map[map_name] = mapping

data["symptom_disease_mapping"] = disease_map

# Write the file
with open('data/symptom_disease_map.json', 'w') as f:
    json.dump(data, f, indent=2)

print("JSON file rebuilt successfully!")
print(f"Symptoms: {len(data['symptoms'])}")
print(f"Diseases: {len(data['diseases'])}")
print(f"Symptom mappings: {len(data['symptom_disease_mapping'])}")